---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: obdx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: obdx
  template:
    metadata:
      labels:
        app: obdx
    spec:
      hostname: gsh
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "gsh.oracle.com"
      containers:
      - name: ohsgsh
        image: iad.ocir.io/id3kyspkytmr/flexcube/ohsgsh:latest
        #image: iad.ocir.io/id3kyspkytmr/oraclefmw-infra_with_patch:12.2.1.4.0
        command: [ "/bin/sh", "-c"]
        args: [ "sleep 180; cd /; yum install tar -y; wget https://objectstorage.us-ashburn-1.oraclecloud.com/p/GEofC4bpkPdb3qkApDYYG2LKHDfgXz3q_6rzgEKDDcBcIcLGr6xK9dK9ecN7pNSB/n/id3kyspkytmr/b/bucket_banco_conceito/o/initializeOHSConfig.sh; sh initializeOHSConfig.sh; while true; do sleep 30; done;" ]
        ports:
        - name: port7777
          containerPort: 7777
        - name: port5557
          containerPort: 5557
        - name: port4443
          containerPort: 4443
      - name: weblogicgsh
        image: iad.ocir.io/id3kyspkytmr/flexcube/weblogicgsh:latest
        #image: iad.ocir.io/id3kyspkytmr/oraclefmw-infra_with_patch:12.2.1.4.0
        command: [ "/bin/sh", "-c"]
        args: [ "sleep 180; cd /; yum install tar -y; wget https://objectstorage.us-ashburn-1.oraclecloud.com/p/oCZ4K4pdurtR4adOwhxJn6GF8VZQ4AhDikLksnnz3T1yEEUAa5p3MNukRUPV8pSw/n/id3kyspkytmr/b/bucket_banco_conceito/o/initializeOBDXConfig.sh; sh initializeOBDXConfig.sh <JDBC URL for OBDX Oracle Database> {AES256}<password>; while true; do sleep 30; done;" ]
        ports:
        - name: port7001
          containerPort: 7001
        - name: port7002
          containerPort: 7002
        - name: port7003
          containerPort: 7003
        - name: port7004
          containerPort: 7004
        - name: port7005
          containerPort: 7005
        - name: port7006
          containerPort: 7006
        - name: port7007
          containerPort: 7007
        - name: port7008
          containerPort: 7008
        - name: port7009
          containerPort: 7009
        - name: port7010
          containerPort: 7010
        - name: port5557
          containerPort: 5557
        - name: port7777
          containerPort: 7777
        - name: port25
          containerPort: 25
        - name: port465
          containerPort: 465
        - name: port587
          containerPort: 587
        livenessProbe:
          httpGet:
            path: /console
            port: 7001
          initialDelaySeconds: 4800
          timeoutSeconds: 30
          periodSeconds: 300
          failureThreshold: 3
#        resources:
#          requests:
#            cpu: "1"
#            memory: "10Gi"
#          limits:
#            cpu: "1"
#            memory: "10Gi"

      restartPolicy: Always
      imagePullSecrets:
      # enter the name of the secret you created
      - name: ocirsecret
---
